### ISSUE TITLE
Mod Sync not loaded

### ISSUE THREAD

**Issue by huuub** [mateoradman/bazarr-bulk#5]
I am running it on linux using bazarr 1.4.2.
I ran on all movies, it connects and goes over the list but in the logs of bazarr for every movie i get "Mod Sync not loaded"

**Comment by mateoradman** [comment]
Hi @huuub,

I suspect there is something that needs to be enabled on your Bazarr instance which allows Syncing and other subtitle operations. Can you please navigate to `http://YOUR_BAZARR_INSTANCE/settings/subtitles` and compare your settings with mine? [Screencast.webm](https://github.com/mateoradman/bazarr-bulk/assets/48420316/ac84a485-7e4e-4362-92e6-1222663eacf8)

**Comment by douglasparker** [comment]
Hey @mateoradman,

I am getting the same error in the logs.

Attached are the requested screenshots.

![IMG_5080](https://github.com/mateoradman/bazarr-bulk/assets/18235822/b0c0cfd7-b4f4-4588-944c-1caf92b14d40)
![IMG_5081](https://github.com/mateoradman/bazarr-bulk/assets/18235822/d0a2da84-2e6c-445d-8e57-7a04aa91d35e)
![IMG_5082](https://github.com/mateoradman/bazarr-bulk/assets/18235822/b08e14a1-8c53-4669-96c9-f076c8a23941)
![IMG_5083](https://github.com/mateoradman/bazarr-bulk/assets/18235822/be54ad03-6f02-484a-b4e6-4108150bf012)

**Comment by mateoradman** [comment]
Thanks for providing screenshots, @douglasparker. Is this Bazarr instance running as a docker container on linux?

**Comment by mateoradman** [comment]
Just fyi this is how a bazarr docker service looks like in my media server's docker-compose.yml file:

```yaml
bazarr:
    image: hotio/bazarr
    container_name: bazarr
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK=022
    volumes:
      - ./bazarr:/config
      - $MEDIADIR:/data
      - $SECOND_MEDIADIR:/data2
    ports:
      - 6767:6767
    restart: unless-stopped
    networks:
      - services
```
